config/routes.rb
Rails.application.routes.draw do
  namespace :card_type do
    resources :documents
  end
  get 'unsplash/search'
  get 'home/index'
  root 'home#index'

  resources :campaigns do
    resources :user_campaigns, path: 'users', only: %i[index create update destroy]

    get 'join', to: 'user_campaigns#new'
    get 'dashboard(/:location_id)', to: 'campaigns#dashboard', as: 'dashboard'

    resources :cards do
      get 'search', on: :collection
      resources :card_links, only: %i[create destroy], path: 'links'
    end

    scope module: 'card_type' do
      resources :quests
      resources :objectives
      resources :locations
      resources :documents
    end
  end

  resources :users, except: :index
  resources :sessions, only: %i[new create destroy]

  get 'sign-up', to: 'users#new', as: 'signup'
  get 'log-in', to: 'sessions#new', as: 'login'
  get 'log-out', to: 'sessions#destroy', as: 'logout'

  %w( 404 500 ).each do |code|
    get code, to: 'errors#show', code: code
  end
end

app/models/card.rb
require 'tip_tap'

module TipTap
	module Nodes
	  class Gallery < Node
		 self.type_name = 'mention'

		 def to_html
			ActionController::Base.helpers.link_to '@' + attrs["label"], attrs["id"]
		 end
	  end
	end
end

class Card < ApplicationRecord
  actable
  belongs_to :campaign
  belongs_to :owner, class_name: 'User'
  has_one :image, as: :imageable
  has_many :card_links
  has_many(
    :related,
    through: :card_links,
    class_name: 'Card',
    source: :to
  )
  accepts_nested_attributes_for :actable
  accepts_nested_attributes_for :image, reject_if: proc { |attributes| !Image.valid_params? attributes }

  default_scope { includes :owner }

  enum :visible, %i[only_me me_and_gm campaign public], prefix: true
  enum :editable, %i[only_me me_and_gm campaign], prefix: true

  validate :visibility_greater_than_editablility

  only_visible :related, :card_links

  after_save :link_mentions
  broadcasts_to ->(card) { [card.campaign, :cards] }

  def broadcast_rendering_with_defaults(options)
    {
      specific.model_name.element.to_sym => specific,
      partial: specific.to_partial_path,
      request_id: Turbo.current_request_id
    }
  end

  def visibility_greater_than_editablility
    unless Card.visibles[visible] >= Card.editables[editable]
      errors.add(:visible, "A card must be visible to the users that can edit it")
    end
  end

  def has_access?(attr, user)
    case attr
    when "only_me"
      user == owner
    when "me_and_gm"
      campaign.owner?(user) || user == owner
    when "campaign"
      campaign.editable?(user)
    when "public"
      campaign.public
    else
      false
    end
  end

  def editable?(user)
    has_access?(editable, user)
  end

  def visible?(user, minimum_visibility = nil)
    minimum_visibility ||= "only_me"
    visibility_value = Card.visibles[visible]
    minimum_visibility_value = Card.visibles[minimum_visibility]
    return false if visibility_value < minimum_visibility_value

    has_access?(visible, user)
  end

  def owner?(user)
    user == owner
  end

  def build_actable(params)
    self.actable = actable_type.constantize.new(params)
  end

  def tiptap_document
    @document ||= TipTap::Document.from_json(content || { "type": "doc", "content": [] })
  end

  def content_html
    ActionController::Base.helpers.safe_join(tiptap_document.map(&:to_html))
  end

  def excerpt
    return "" unless content
    return @excerpt if @excerpt

    first_paragraph_index = content["content"].find_index { |block| block["type"] == "paragraph" }

    return "" unless first_paragraph_index

    until_first_paragraph = content["content"].take(first_paragraph_index + 1)

    document = TipTap::Document.from_json({
      "type": "doc",
      "content": until_first_paragraph
    })

    @excerpt = ActionController::Base.helpers.safe_join(document.map(&:to_html))
  end

  def self.search(query)
    where('lower(title) LIKE :search', search: "%#{query}%")
  end

  def self.types
    CardType.constants
      .map { ('CardType::' + _1.to_s).constantize }
      .select { _1 < ApplicationRecord }
  end

  def icon
    specific.icon
  end

  def friendly_title
    if title.blank?
      unnamed_title
    else
      title
    end
  end

  def unnamed_title
    "Unnammed #{specific.model_name.human}"
  end

  def link_mentions
    def walk_tree(tree, &block)
      yield tree

      if tree["content"]
        tree["content"].each { walk_tree(_1, &block) }
      end

      return tree
    end

    return unless content

    walk_tree(content) do |node|
      if node["type"] == "mention"
        params = Rails.application.routes.recognize_path(node["attrs"]["id"])
        CardLink.find_or_create_by(card_id: id, to_id: params[:id])
      end
    end
  end

  def self.icon_for_group(group)
    case group
    when "only_me"
      "fa fa-lock"
    when "me_and_gm"
      "fa fa-user-group"
    when "campaign"
      "fa fa-users"
    when "public"
      "fa fa-earth-europe"
    end
  end
end

app/models/card_type.rb
module CardType
  def self.table_name_prefix
    'card_type_'
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_campaign
  before_action :set_card, only: %i[show update destroy]

  layout "header_and_content"

  # GET /cards/new
  def new
    @types = Card.types
  end

  def show
    redirect_to [@campaign, @card.specific]
  end

  def search
    query = @campaign._cards.where(
      'lower(title) LIKE :query',
      query: "%#{params[:q]}%"
    )

    if params[:count]
      query = query.limit(params[:count].to_i)
    end

    cards = query.filter { _1.visible?(current_user) }

    render json: {
      success: true,
      items: cards.map do |card|
        {
          name: card.friendly_title,
          href: polymorphic_path([@campaign, card.specific]),
          description: card.description || card.excerpt
        }
      end
    }
  end

  # POST /cards
  def create
    @card = Card.new(card_params)
    @card.campaign = @campaign
    @card.owner = current_user

    if @card.save!
      if params[:redirect_back]
        redirect_back fallback_location: [@campaign, @card.specific], allow_other_host: false
      else
        redirect_to [@campaign, @card.specific], notice: 'Card was successfully created.'
      end
    else
      @card = @card.specific
      render :new
    end
  end

  # PATCH/PUT /cards/1
  def update
    if @card.update(card_params)
      respond_to do |format|
        format.html { redirect_to [@campaign, @card.specific], notice: 'Card was successfully updated.' }
        format.json { render json: @card }
      end

    else
      @card = @card.specific
      render :show
    end
  end

  # DELETE /cards/1
  def destroy
    @card.destroy
    redirect_to campaign_cards_url(@campaign), notice: 'Card was successfully destroyed.'
  end

  private

  def set_campaign
    @campaign = Campaign.find_by_slug!(params[:campaign_id])
    raise ActiveRecord::RecordNotFound unless @campaign.visible?(current_user)
  end

  def set_card
    @card = Card.find_by_id!(params[:id])
    raise ActiveRecord::RecordNotFound unless @card.visible?(current_user)
  end

  # Only allow a list of trusted parameters through.
  def card_params
    if params[:card][:actable_type]
      unless params[:card][:actable_type].start_with?('CardType::')
        raise ActionController::BadRequest
      end

      actable_attributes = params[:card][:actable_type].constantize.permitted_attributes
    else
      actable_attributes = []
    end

    params.require(:card).permit(
      :title, :description, :slug, :campaign_id, :actable_type,
      :visible, :editable,
      content: {},
      actable_attributes: %i[id] + actable_attributes,
      image_attributes: [
        :id,
        :actable_type,
        { actable_attributes: %i[id unsplash_id] }
      ]
    )
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_card.html.erb
<div class="card" id="<%= dom_id(card) %>">
	<div class="card-actions">
		<% if local_assigns.key?(:card_link) && card.editable?(current_user) %>
			<%= button_to [card.campaign, card, card_link], method: :delete do %>
				<i class="fa fa-chain-broken"></i>
			<% end %>
		<% end %>
	</div>

	<%= link_to [card.campaign, card.specific] do %>
		<%= render 'image_header', image: card.image do %>
			<%= render 'icon_header',
				level: 3,
				title: card.friendly_title,
				icon: card.icon,
				label: card.specific.model_name.human
			%>
		<% end %>
	<% end %>

	<% if card.description.blank? %>
		<%= card.excerpt %>
	<% else %>
		<p><%= card.description %></p>
	<% end %>

	<%= yield %>
</div>

app/views/cards/_content.html.erb
<div
	class="editor"
	<% if card.editable? current_user %>
		data-controller="editor"
		data-editor-action-value="<%= polymorphic_path([card.campaign, card.acting_as]) %>"
		data-editor-search-value="<%= search_campaign_cards_path(card.campaign) %>"
	<% end %>
>

	<% if card.editable? current_user %>
		<script type="application/json" data-editor-target="content">
			<%= card.content.to_json.html_safe %>
		</script>

		<div data-editor-target="bubbleMenu">
			<button data-action="click->editor#format" data-editor-format-param="toggleBold">
				<i class="fa fa-bold"></i>
			</button>
			<button data-action="click->editor#format" data-editor-format-param="toggleItalic">
				<i class="fa fa-italic"></i>
			</button>
		</div>

		<div data-editor-target="floatingMenu">
			<button data-action="click->editor#format" data-editor-format-param="toggleHeading" data-editor-args-param='{ "level": 1 }'>
				<i class="fa fa-header"></i>
				<sub>1</sub>
			</button>
			<button data-action="click->editor#format" data-editor-format-param="toggleHeading" data-editor-args-param='{ "level": 2 }'>
				<i class="fa fa-header"></i>
				<sub>2</sub>
			</button>
			<button data-action="click->editor#format" data-editor-format-param="toggleBlockquote">
				<i class="fa fa-quote-left"></i>
			</button>
		</div>

		<div data-editor-target="editor"></div>
	<% end %>

	<div data-editor-target="rendered">
		<%= card.content_html %>
	</div>
</div>

app/views/cards/_form.html.erb
<% content_for :card_nav do %>
  <%= link_to card.persisted? ? [card.campaign, card.specific] : [:new, card.campaign, :card] do %>
    <i class="fa fa-arrow-left"></i>
    Back
  <% end %>
<% end %>

<%= form_with(model: [@campaign, card], id: :card_form, html: { class: :grid }, data: { controller: 'autosave', action: 'input->autosave#save change->autosave#save' }) do |form| %>
  <% if card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
        <% card.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if card.owner?(current_user) %>
    <div class="card">
      <div class="o-forms-field">
        <%= form.label :visible, class: 'o-forms-title' do %>
          <span class="o-forms-title__main">
            Visible to
          </span>
        <% end %>
        <span class="o-forms-input o-forms-input--radio-box">
          <span class="o-forms-input--radio-box__container">
            <% Card.visibles.keys.each do |visibility| %>
              <%= form.label :visible, value: visibility, title: visibility.humanize do %>
                <%= form.radio_button :visible, visibility %>
                <span class="o-forms-input__label">
                  <i class="<%= Card.icon_for_group(visibility) %>"></i>
                </span>
              <% end %>
            <% end %>
          </span>
        </span>
      </div>
      <div class="o-forms-field">
        <%= form.label :editable, class: 'o-forms-title' do %>
          <span class="o-forms-title__main">
            Editable by
          </span>
        <% end %>
          <span class="o-forms-input o-forms-input--radio-box">
            <span class="o-forms-input--radio-box__container">
              <% Card.editables.keys.each do |editability| %>
                <%= form.label :editable, value: editability, title: editability.humanize do %>
                  <%= form.radio_button :editable, editability %>
                  <span class="o-forms-input__label">
                    <i class="<%= Card.icon_for_group(editability) %>"></i>
                  </span>
                <% end %>
              <% end %>
            </span>
          </span>
      </div>
    </div>
  <% end %>

  <div class="card">
    <div class="field">
      <%= render 'images/form', image: card.image, form: form %>
    </div>
  </div>

  <%= form.hidden_field :actable_type %>

  <%= yield form %>
<% end %>

app/views/cards/_header.html.erb
<% allow_edit = local_assigns.has_key?(:allow_edit) ? allow_edit : card.editable?(current_user) %>

<% content_for :header do %>
   <% if card.parent %>
      <%= link_to [card.parent.campaign, card.parent] do %>
      	<% if card.parent.specific.model_name == card.specific.model_name %>
            <h2><%= card.parent.friendly_title %></h2>
         <% else %>
            <%= render 'icon_header', {
               level: 2,
               title: card.parent.friendly_title,
               icon: card.parent.icon,
               label: card.parent.specific.model_name.human
            } %>
         <% end %>
      <% end %>
   <% end %>

   <%= render 'icon_header', icon: card.icon, label: card.specific.model_name.human do %>
      <% if allow_edit %>
         <%= form_with model: [card.campaign, card.acting_as], data: { controller: 'autosave', action: 'input->autosave#save' }, class: 'inline-form' do |form| %>
            <%= form.text_field :title,
               class: 'inline-input autosize-input',
               data: {
                  controller: 'auto-size-input',
                  action: 'input->auto-size-input#update',
                  turbo_permanent: true
               },
               placeholder: "#{card.specific.unnamed_title}…",
               autofocus: card.title.blank?
            %>
         <% end %>
      <% else %>
         <%= card.friendly_title %>
      <% end %>
   <% end %>

   <% if allow_edit %>
      <%= form_with model: [card.campaign, card.acting_as], data: { controller: 'autosave', action: 'input->autosave#save' } do |form| %>
         <%= form.text_field :description,
            class: 'inline-input autosize-input',
            data: {
               controller: 'auto-size-input',
               action: 'input->auto-size-input#update',
               turbo_permanent: true
            },
            placeholder: 'Description…'
         %>
      <% end %>
   <% else %>
      <%= card.description %>
   <% end %>
<% end %>

app/views/cards/new.html.erb
<% content_for :header do %>
   <h1>Add something...</h1>
<% end %>

<% content_for :nav do %>
   <%= link_to @campaign do %>
      <h3><%= @campaign.name %></h3>
   <% end %>
<% end %>

<div class="grid">
   <% @types.each do |type| %>
      <% card = type.new(card: Card.new) %>
      <%= form_with model: [@campaign, card.card], html: { class: :card }, namespace: type.model_name do |f| %>
         <%= f.hidden_field :actable_type %>
         <%= f.fields_for :actable, card.actable do |a| %>
            <%= a.hidden_field :id %>
         <% end %>

         <%= f.button class: 'link-button' do %>
            <header>
               <%= render 'icon_header', level: 3, title: type.model_name.human, icon: type.icon, label: type.model_name.human %>
            </header>

            <p><%= type.description %></p>
         <% end %>
      <% end %>
   <% end %>
</div>