config/routes.rb
Rails.application.routes.draw do
  namespace :card_type do
    resources :documents
  end
  get 'unsplash/search'
  get 'home/index'
  root 'home#index'

  resources :campaigns do
    resources :user_campaigns, path: 'users', only: %i[index create update destroy]

    get 'join', to: 'user_campaigns#new'
    get 'dashboard(/:location_id)', to: 'campaigns#dashboard', as: 'dashboard'

    resources :cards do
      get 'search', on: :collection
      resources :card_links, only: %i[create destroy], path: 'links'
    end

    scope module: 'card_type' do
      resources :quests
      resources :objectives
      resources :locations
      resources :documents
    end
  end

  resources :users, except: :index
  resources :sessions, only: %i[new create destroy]

  get 'sign-up', to: 'users#new', as: 'signup'
  get 'log-in', to: 'sessions#new', as: 'login'
  get 'log-out', to: 'sessions#destroy', as: 'logout'

  %w( 404 500 ).each do |code|
    get code, to: 'errors#show', code: code
  end
end

app/models/user_campaign.rb
class UserCampaign < ApplicationRecord
  belongs_to :user
  belongs_to :campaign
  enum :access, %i[owner member]
  validates :user_id, uniqueness: { scope: :campaign_id }
end

app/controllers/user_campaigns_controller.rb
class UserCampaignsController < ApplicationController
	before_action :set_campaign
	layout "header_and_content"

	def index; end

	def new
		@token = params[:token]
		raise HttpException::Forbidden unless @campaign.invite_token == @token
		redirect_to @campaign if @campaign.users.where(id: current_user.id).exists?
	end

	def create
		if params.has_key? :token
			create_with_token
		else
			create_invite
		end
	end

	def create_with_token
		user_campaign = UserCampaign.new(join_params.merge(
			campaign: @campaign,
			access: :member,
			accepted: true
		))

		token_valid = params[:token] == @campaign.invite_token
		user_is_self = user_campaign.user == current_user

		raise HttpException::Forbidden unless token_valid and user_is_self

		if user_campaign.save
			redirect_to @campaign
		else
			render :new
		end
	end

	def create_invite
		raise HttpException::Forbidden unless @campaign.owner? current_user

		user = User.find_by_username! params[:user_campaign][:user][:username]
		user_campaign = UserCampaign.new(
			user: user,
			campaign: @campaign,
			access: params[:user_campaign][:access]
		)

		if user_campaign.save
			redirect_to campaign_user_campaigns_path(@campaign)
		else
			render :index
		end
	end

	def update
		user_campaign = UserCampaign.find(params[:id])

		raise HttpException::Forbidden unless user_campaign.user == current_user

		if user_campaign.update(accept_params)
			redirect_to user_campaign.campaign
		else
			redirect_to user_campaign.campaign # TODO what
		end
	end

	def destroy
		user_campaign = UserCampaign.find(params[:id])
		deleting_self = user_campaign.user == current_user

		raise HttpException::Forbidden unless deleting_self || @campaign.owner?(current_user)

		user_campaign.destroy
		if deleting_self
			redirect_to current_user
		else
			redirect_to campaign_user_campaigns_path(@campaign)
		end
	end

	def set_campaign
		@campaign = Campaign.find_by_slug!(params[:campaign_id])
		@image = @campaign.image
	end

	def accept_params
		params.require(:user_campaign).permit(:accepted)
	end

	def join_params
		params.require(:user_campaign).permit(:user_id)
	end
end

app/views/user_campaigns/index.html.erb
<% content_for :title, "#{@campaign.name} members" %>

<% content_for :nav do %>
  <%= link_to @campaign do %>
    <h3><%= @campaign.name %></h3>
  <% end %>
<% end %>

<% content_for :header do %>
  <h1><%= @campaign.name %></h1>

  <% unless @campaign.tagline.blank? %>
    <p><%= @campaign.tagline %></p>
  <% end %>
<% end %>

<div class="grid">
  <div class="paper wide">
    <h3>Members</h3>
    <table>
      <% @campaign.campaign_users.order(:access).each do |campaign_user| %>
        <tr>
          <td width="100%">
            <%= render campaign_user.user, campaign_user: campaign_user %>
          </td>
          <td align="right">
            <span class="badge">
              <%= campaign_user.access.to_s.humanize %>
            </span>
          </td>
          <% if @campaign.owner? current_user && @campaign.campaign_users.count > 1 %>
            <td>
              <%= button_to [@campaign, campaign_user], method: :delete do %>
                <i class="fa fa-times"></i>
              <% end %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </table>
  </div>

  <% if @campaign.owner? current_user %>
    <div class="card">
      <h3>Invite...</h3>
      <%= form_with(model: [@campaign, @campaign.campaign_users.build]) do |form| %>
        <%= form.fields_for :user do |f| %>
          <div class="field">
            <%= f.label :username %>
            <%= f.text_field :username %>
          </div>
        <% end %>
        <div class="field">
          <%= form.label :access %>
          <%= form.select :access, UserCampaign.accesses.keys.reverse.map { [_1.humanize, _1] } %>
        </div>
        <%= form.submit %>
      <% end %>
    </div>

    <% if @campaign.pending_invites.exists? %>
      <div class="card">
        <h3>Pending invites</h3>
        <ul>
          <% @campaign.pending_invites.each do |campaign_user| %>
            <li>
            <%= render campaign_user.user, campaign_user: campaign_user %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="card">
      <h3>Invite link</h3>
      <p>This link allows anybody to join your campaign. Use with caution.</p>
      <%= text_field_tag :join, campaign_join_url(@campaign, {token: @campaign.invite_token}), readonly: true %>
    </div>
  <% end %>
</div>

app/views/user_campaigns/new.html.erb
<% content_for :title, "Join #{@campaign.name}" %>

<% content_for :header do %>
  <h1>Join <%= @campaign.name %></h1>

  <% unless @campaign.tagline.blank? %>
    <p><%= @campaign.tagline %></p>
  <% end %>
<% end %>

<div class="grid">
	<%# TODO login/register %>
	<div class="card">
		<%= form_with model: [@campaign, @campaign.campaign_users.build(user: current_user)] do |form| %>
			<%= hidden_field_tag :token, @token %>
			<%= form.hidden_field :user_id %>
			<%= form.submit 'Join' %>
		<% end %>
	</div>
</div>